upstream django_gunicorn {
    server web:8000;
}

# --- SERVIDOR HTTP (Porta 80) ---
server {
    listen 80;
    
    server_name gtreinos-marco.duckdns.org; 

    # Rota exigida pelo Certbot para validar o domínio (DEIXE DESCOMENTADO)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # === REDIRECIONAMENTO HTTPS ===
    # Quando o certificado estiver pronto, DESCOMENTE o location abaixo 
    # e COMENTE os blocos de favicon, static, media e / que estão logo a seguir.
    # location / {
    #     return 301 https://$host$request_uri;
    # }

    # Ignora logs de favicon
    location = /favicon.ico { 
        access_log off; 
        log_not_found off; 
    }

    # ROTEAMENTO DE ESTÁTICOS
    location /static/ {
        alias /app/static_root/;
    }

    # ROTEAMENTO DE MÍDIA
    location /media/ {
        alias /app/media/;
    }

    # ROTEAMENTO DINÂMICO
    location / {
        proxy_pass http://django_gunicorn;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# --- SERVIDOR HTTPS (Porta 443) ---
# DESCOMENTE este bloco inteiro APÓS gerar o certificado no servidor AWS
# server {
#     listen 443 ssl;
#     server_name gtreinos-marco.duckdns.org;
#
#     ssl_certificate /etc/letsencrypt/live/gtreinos-marco.duckdns.org/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/gtreinos-marco.duckdns.org/privkey.pem;
#
#     location = /favicon.ico { 
#         access_log off; 
#         log_not_found off; 
#     }
#
#     location /static/ {
#         alias /app/static_root/;
#     }
#
#     location /media/ {
#         alias /app/media/;
#     }
#
#     location / {
#         proxy_pass http://django_gunicorn;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }
# }