# Generated by Django 6.0.4 on 2026-04-20 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_realizacao', models.DateTimeField(blank=True, null=True)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('repeticoes', models.IntegerField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('esta_concluido', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='users.aluno')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercicios_criados', to='users.professor')),
            ],
        ),
    ]
